---
- name: Install mariadb server
  become_user: root
  become: true
  ansible.builtin.apt:
    pkg:
      - libmysqlclient-dev
      - mariadb-client
      - mariadb-server
      - python3-mysqldb
      - python3-pymysql
    state: present
    update_cache: true

- name: Add configuration
  become: true
  become_user: root
  ansible.builtin.template:
    src: files/my.cnf
    dest: /etc/mysql/
    owner: root
    group: root
    mode: "0644"
    backup: true
  register: mysql_config

- name: Check if mysql config file has changed
  debug:
    var: mysql_config.changed

- name: Restart and enable mysql
  become: true
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true
  when: mysql_config.changed

- name: Removes anonymous user account for localhost
  community.mysql.mysql_user:
    check_implicit_admin: true
    login_password: 'password'
    name: ''
    host: localhost
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    check_implicit_admin: true
    login_password: 'password'
    name: ''
    host_all: true
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Remove test database
  community.mysql.mysql_db:
    check_implicit_admin: true
    login_password: 'password'
    db: test
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Change root user password and permissions
  community.mysql.mysql_user:
    check_implicit_admin: true
    host: "{{ item }}"
    login_user: root
    login_password: 'password'
    name: root
    password: 'password'
    priv: "*.*:ALL,GRANT"
    login_unix_socket: /run/mysqld/mysqld.sock
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
