---
- name: Check that bench repo is initiated
  ansible.builtin.stat:
    path: /home/{{ ansible_user }}/erpnext
  register: erpnext_initiated

- name: Display if bench repo exists
  ansible.builtin.debug:
    var: erpnext_initiated.stat.exists

- name: Init erpnext bench repository
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: |
    cd /home/{{ ansible_user }}
    bench init erpnext --frappe-branch version-15 --ignore-exist
  when: not erpnext_initiated.stat.exists
  changed_when: erpnext_initiated.stat.exists

- name: Change permissions
  ansible.builtin.file:
    dest: /home/{{ ansible_user }}
    mode: o=rX
    recurse: true
  when: not erpnext_initiated.stat.exists
  changed_when: erpnext_initiated.stat.exists

- name: Import erpnext application
  become: false
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: |
    cd /home/{{ ansible_user }}/erpnext
    bench get-app --branch version-15 erpnext
  when: not erpnext_initiated.stat.exists
  changed_when: erpnext_initiated.stat.exists

- name: Import payments application
  become: false
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: |
    cd /home/{{ ansible_user }}/erpnext
    bench get-app payments --branch version-15
  when: not erpnext_initiated.stat.exists
  changed_when: erpnext_initiated.stat.exists

- name: Import hrms application
  become: false
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: |
    cd /home/{{ ansible_user }}/erpnext
    bench get-app hrms --branch version-15
  when: not erpnext_initiated.stat.exists
  changed_when: erpnext_initiated.stat.exists
