---
- name: Check that bench repo is initiated
  stat:
    path: /home/{{ ansible_user }}/spectrum
  register: spectrum_initiated

- name: Init spectrum bench repository
  become_user: "{{ ansible_user }}"
  become: yes
  shell: |
    cd /home/{{ ansible_user }}
    bench init spectrum --frappe-branch version-15 --ignore-exist
  when: spectrum_initiated.stat.exists == False

- name: Change permissions
  file:
    dest: /home/{{ ansible_user }}
    mode: o=rX
    recurse: yes
  when: spectrum_initiated.stat.exists == False

- name: Import erpnext application
  become_user: "{{ ansible_user }}"
  shell: |
    cd /home/{{ ansible_user }}/spectrum
    bench get-app --branch version-15 erpnext
  when: spectrum_initiated.stat.exists == False

- name: Import payments application
  become_user: "{{ ansible_user }}"
  shell: |
    cd /home/{{ ansible_user }}/spectrum
    bench get-app payments --branch version-15
  when: spectrum_initiated.stat.exists == False

- name: Import hrms application
  become_user: "{{ ansible_user }}"
  shell: |
    cd /home/{{ ansible_user }}/spectrum
    bench get-app hrms --branch version-15
  when: spectrum_initiated.stat.exists == False
