---
- name: Check that erpnext.local site is installed
  stat:
    path: /home/{{ ansible_user }}/erpnext/site/erpnext.local
  register: site_installed

- name: Create erpnext site
  become_user: "{{ ansible_user }}"
  shell: |
    cd /home/{{ ansible_user }}/erpnext
    bench new-site erpnext.local --mariadb-root-username root --mariadb-root-password password --admin-password password --force
    bench --site erpnext.local enable-scheduler
    bench --site erpnext.local set-maintenance-mode off
  when: site_installed.stat.exists == False

- name: Install erpnext on erpnext site
  become_user: "{{ ansible_user }}"
  shell: |
    cd /home/{{ ansible_user }}/erpnext
    bench --site erpnext.local install-app erpnext
  when: site_installed.stat.exists == False

- name: Install payments on erpnext site
  become_user: "{{ ansible_user }}"
  shell: |
    cd /home/{{ ansible_user }}/erpnext
    bench --site erpnext.local install-app payments
  when: site_installed.stat.exists == False

- name: Setup erpnext producion
  become_user: "{{ ansible_user }}"
  shell: |
    cd /home/{{ ansible_user }}/erpnext
    sudo bench setup supervisor
    sudo bench setup redis
    sudo bench setup production {{ ansible_user }} --yes
  when: site_installed.stat.exists == False

- name: Install hrms on erpnext site
  become_user: "{{ ansible_user }}"
  shell: |
    cd /home/{{ ansible_user }}/erpnext
    bench --site erpnext.local install-app hrms
  when: site_installed.stat.exists == False
