---
- name: Install nginx
  become_user: root
  become: true
  ansible.builtin.apt:
    pkg: nginx
    state: present
    update_cache: true

- name: Disable default config
  become_user: root
  become: true
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  register: nginx_config

- name: Check if default config was removed
  debug:
    var: nginx_config.changed

- name: Restart and enable nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
  when: nginx_config.changed
