---
- name: Install nginx
  become_user: root
  become: yes
  ansible.builtin.apt:
    pkg: nginx
    state: latest
    update_cache: true

- name: Disable default config
  become_user: root
  become: yes
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart and enable nginx
  become: yes
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Reload Nginx
  become: yes
  ansible.builtin.service:
    name: nginx
    state: reloaded
