---
- name: Add hashicorp apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /etc/apt/trusted.gpg.d/hashicorp.gpg
    state: present

- name: Add hashicorp repository
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com jammy main
    state: present
    update_cache: true
