---
- name: Deploy hashicorp tools
  hosts: localhost
  roles:
    - { role: awscli,       tags: awscli      }
    - { role: hashicorp,    tags: hashicorp   }
    - { role: packer,       tags: packer      }
    - { role: terraform,    tags: terraform   }
